Filename : notebook_01.ipynb <br>
Description : NumPy usage exampels

---

In [2]:
import numpy as np

print(np.__version__)

2.5.2


---

1. NumPy Basic

**คำอธิบาย:** NumPy เป็นไลบรารีหลักสำหรับการคำนวณเชิงตัวเลขใน Python โดยโครงสร้างข้อมูลพื้นฐานที่สุดคือ **ndarray** (N-dimensional array) ซึ่งเก็บข้อมูลชนิดเดียวกันทั้งหมดและคำนวณได้เร็วกว่า list ปกติมาก

เซลล์นี้แสดงวิธีสร้างอาร์เรย์ 3 แบบ:
- `np.array([...])` - สร้างอาร์เรย์จาก list โดยตรง
- `np.arange(start, stop, step)` - สร้างอาร์เรย์ของค่าต่อเนื่องตามช่วงและ step ที่กำหนด (คล้าย `range()` ของ Python)
- `np.linspace(start, stop, num)` - สร้างอาร์เรย์ของค่าที่เว้นระยะเท่า ๆ กัน `num` ค่า ระหว่าง `start` ถึง `stop` (รวมค่าปลายทั้งสองด้าน)

In [3]:
### Creating arrays ###

arr = np.array([1, 2, 3, 4, 5])
print("np.array:", arr)

## Example 1: np.arange
arange_arr = np.arange(0, 10, 2)                    # start=0, stop=10, step=2
print("np.arange:", arange_arr)

## Example 2: np.linspace
linspace_arr = np.linspace(0, 1, 5)                 # start=0, stop=1, 5 evenly spaced values
print("np.linspace:", linspace_arr)

np.array: [1 2 3 4 5]
np.arange: [0 2 4 6 8]
np.linspace: [0.   0.25 0.5  0.75 1.  ]


**คำอธิบาย:** เมื่อสร้างอาร์เรย์ 2 มิติ (เช่น เมทริกซ์) แล้ว มี attribute สำคัญที่ใช้ตรวจสอบคุณสมบัติของอาร์เรย์ได้ทันที:
- `.dtype` - ชนิดข้อมูลของสมาชิกในอาร์เรย์ (เช่น int64, float64) โดย NumPy จะกำหนดชนิดข้อมูลเดียวกันให้ทุกสมาชิกในอาร์เรย์เดียวกัน
- `.shape` - ขนาดของอาร์เรย์ในรูปแบบ (จำนวนแถว, จำนวนคอลัมน์)
- `.ndim` - จำนวนมิติของอาร์เรย์ (เช่น 1 มิติ = เวกเตอร์, 2 มิติ = เมทริกซ์)

In [4]:
### Data types and shape ###

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

## Example 1: .dtype
print("arr_2d dtype:", arr_2d.dtype)                # data type of elements

## Example 2: .shape
print("arr_2d shape:", arr_2d.shape)                # dimensions (rows, columns)

## Example 3: .ndim
print("arr_2d ndim:", arr_2d.ndim)                  # number of dimensions

arr_2d dtype: int64
arr_2d shape: (2, 3)
arr_2d ndim: 2


**คำอธิบาย:** การเข้าถึงข้อมูลในอาร์เรย์ 2 มิติทำได้ 3 รูปแบบหลัก:
- **Indexing** - เข้าถึงค่าตำแหน่งเดียวด้วย `arr[row, col]` เช่น `arr_2d[0, 1]` คือค่าที่แถว 0 คอลัมน์ 1
- **Slicing** - เลือกช่วงของแถว/คอลัมน์ด้วย `:` เช่น `arr_2d[0, :]` คือทั้งแถวที่ 0, `arr_2d[:, 0]` คือทั้งคอลัมน์ที่ 0 และ `arr_2d[0:2, 1:3]` คือช่วงแถว 0-1 ตัดกับช่วงคอลัมน์ 1-2
- **Boolean Indexing** - ใช้เงื่อนไข (เช่น `arr_2d > 3`) เป็นตัวกรอง เพื่อดึงเฉพาะค่าที่ตรงตามเงื่อนไขออกมาเป็นอาร์เรย์ 1 มิติ

In [5]:
### Accessing data ###

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

## Example 1: Indexing 
print("arr_2d[0, 1]:", arr_2d[0, 1])                # element at row 0, col 1 >>> 2
print("arr_2d[1, 2]:", arr_2d[1, 2])                # element at row 1, col 2 >>> 6

## Example 2: Slicing 
print("\nFirst row:", arr_2d[0, :])                 # row 0 >>> [1 2 3]
print("First column:", arr_2d[:, 0])                # column 0 >>> [1 4]
print("Submatrix:\n", arr_2d[0:2, 1:3])             # slice rows 0–1, cols 1–2 >>> [[2 3],[5 6]]

## Example 3: Boolean Indexing 
print("\nElements > 3:", arr_2d[arr_2d > 3])        # all elements greater than 3
print("Elements even:", arr_2d[arr_2d % 2 == 0])    # all even elements

arr_2d[0, 1]: 2
arr_2d[1, 2]: 6

First row: [1 2 3]
First column: [1 4]
Submatrix:
 [[2 3]
 [5 6]]

Elements > 3: [4 5 6]
Elements even: [2 4 6]


---

2. Basic Data Manipulation

**คำอธิบาย:** การปรับรูปร่าง (reshape) อาร์เรย์เป็นการจัดเรียงข้อมูลชุดเดิมใหม่ให้มีจำนวนแถว/คอลัมน์ต่างไปจากเดิม โดยจำนวนสมาชิกทั้งหมดต้องเท่าเดิมเสมอ:
- `.reshape(rows, cols)` - เปลี่ยนรูปร่างอาร์เรย์ตามจำนวนแถวและคอลัมน์ที่กำหนด
- `.ravel()` - ทำให้อาร์เรย์แบนราบเป็น 1 มิติ โดยคืนค่าเป็น **view** (ข้อมูลอ้างอิงอาร์เรย์เดิม แก้ค่าใน view จะกระทบต้นฉบับด้วย)
- `.flatten()` - ทำให้อาร์เรย์แบนราบเป็น 1 มิติเช่นกัน แต่คืนค่าเป็น **copy** (สำเนาข้อมูลใหม่ แก้ไขไม่กระทบต้นฉบับ)

In [6]:
### Reshaping arrays ###

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original arr_2d:\n", arr_2d)

# Example 1: .reshape
reshaped = arr_2d.reshape(3, 2)                     # reshape to 3 rows, 2 columns
print("\nReshaped (3x2):\n", reshaped)

# Example 2: .ravel 
raveled = arr_2d.ravel()                            # returns flattened view (1D)
print("\nRaveled (view):", raveled)

# Example 3: .flatten 
flattened = arr_2d.flatten()                        # returns flattened copy (1D)
print("\nFlattened (copy):", flattened)

Original arr_2d:
 [[1 2 3]
 [4 5 6]]

Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Raveled (view): [1 2 3 4 5 6]

Flattened (copy): [1 2 3 4 5 6]


**คำอธิบาย:** การรวมและแบ่งอาร์เรย์มีฟังก์ชันหลักดังนี้:
- `np.concatenate((a, b), axis=0)` - ต่ออาร์เรย์ตามแนวแถว (axis=0) หรือแนวคอลัมน์ (axis=1)
- `np.vstack((a, b))` - ซ้อนอาร์เรย์ในแนวตั้ง (เพิ่มแถว) เทียบเท่ากับ `concatenate(axis=0)`
- `np.hstack((a, b))` - ซ้อนอาร์เรย์ในแนวนอน (เพิ่มคอลัมน์) เทียบเท่ากับ `concatenate(axis=1)`
- `np.split(arr, n, axis=1)` - แบ่งอาร์เรย์ออกเป็น `n` ส่วนเท่า ๆ กันตามแนวที่กำหนด (`axis=1` คือแบ่งตามคอลัมน์)

In [7]:
### Combining and splitting arrays ###

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Example 1: np.concatenate 
concat = np.concatenate((a, b), axis=0)             # Concatenate along rows (axis=0)
print("np.concatenate (axis=0):\n", concat)

concat2 = np.concatenate((a, b), axis=1)            # Concatenate along column (axis=0)
print("\nnp.concatenate (axis=1):\n", concat2)

# Example 2: np.vstack 
vstacked = np.vstack((a, b))                        # Stack arrays vertically (row-wise)
print("\nnp.vstack:\n", vstacked)

# Example 3: np.hstack 
hstacked = np.hstack((a, b))                        # Stack arrays horizontally (column-wise)
print("\nnp.hstack:\n", hstacked)

# Example 4: np.split 
split_arr = np.split(hstacked, 2, axis=1)           # Split array into 2 parts along columns (axis=1)
print("\nnp.split (axis=1):")
for i, part in enumerate(split_arr):
    print(f"Part {i+1}:\n", part)


np.concatenate (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.concatenate (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

np.vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.hstack:
 [[1 2 5 6]
 [3 4 7 8]]

np.split (axis=1):
Part 1:
 [[1 2]
 [3 4]]
Part 2:
 [[5 6]
 [7 8]]


**คำอธิบาย:** ข้อมูลตัวเลขอาจมีค่าที่ขาดหายในรูปแบบ `np.nan` (Not a Number) ซึ่ง NumPy มีฟังก์ชันช่วยจัดการโดยเฉพาะ:
- `np.isnan(arr)` - ตรวจสอบทีละค่าว่าเป็น `NaN` หรือไม่ คืนค่าเป็นอาร์เรย์ boolean
- `np.nan_to_num(arr, nan=value)` - แทนที่ค่า `NaN` ทั้งหมดด้วยค่าที่กำหนด (default คือ 0) ซึ่งต่างจากค่า `NaN` ตรงที่สามารถนำไปคำนวณต่อได้ทันที โดยไม่ทำให้ผลลัพธ์กลายเป็น `NaN` ไปด้วย

In [8]:
### Handling missing values ###

arr = np.array([1, 2, np.nan, 4, np.nan])
print("Original array:", arr)


# Example 1: np.isnan 
mask = np.isnan(arr)                                # Returns a boolean array indicating which elements are NaN
print("np.isnan result:", mask)


# Example 2: np.nan_to_num 
arr_replaced = np.nan_to_num(arr, nan=0)            # Replace NaN with 0 (default), or specify another value
print("np.nan_to_num (replace NaN with 0):", arr_replaced)

arr_replaced2 = np.nan_to_num(arr, nan=-1)
print("np.nan_to_num (replace NaN with -1):", arr_replaced2)


Original array: [ 1.  2. nan  4. nan]
np.isnan result: [False False  True False  True]
np.nan_to_num (replace NaN with 0): [1. 2. 0. 4. 0.]
np.nan_to_num (replace NaN with -1): [ 1.  2. -1.  4. -1.]


---

3. Computation and Transformation

**คำอธิบาย:** NumPy มีฟังก์ชันคำนวณค่าสถิติพื้นฐานของอาร์เรย์ให้ใช้งานโดยตรง โดยคำนวณจากสมาชิกทุกตัวในอาร์เรย์:
- `np.sum()` - ผลรวมของค่าทั้งหมด
- `np.mean()` - ค่าเฉลี่ย
- `np.std()` - ส่วนเบี่ยงเบนมาตรฐาน (วัดการกระจายตัวของข้อมูล)
- `np.min()` / `np.max()` - ค่าต่ำสุด/สูงสุดในอาร์เรย์

In [9]:
### Numerical operations ###
arr = np.array([1, 2, 3, 4, 5, 6])
print("Array:", arr)

# Example 1: np.sum
print("Sum:", np.sum(arr))                          # total of all elements

# Example 2: np.mean 
print("Mean:", np.mean(arr))                        # average value

# Example 3: np.std 
print("Standard Deviation:", np.std(arr))           # measure of spread

# Example 4: np.min 
print("Minimum:", np.min(arr))                      # smallest value

# Example 5: np.max 
print("Maximum:", np.max(arr))                      # largest value


Array: [1 2 3 4 5 6]
Sum: 21
Mean: 3.5
Standard Deviation: 1.707825127659933
Minimum: 1
Maximum: 6


**คำอธิบาย:** นอกจากฟังก์ชันสถิติแล้ว NumPy ยังมีฟังก์ชันคณิตศาสตร์ที่คำนวณแบบ element-wise (คำนวณทีละค่าในอาร์เรย์พร้อมกันทั้งหมด) ได้แก่:
- `np.log()` - ลอการิทึมธรรมชาติ (ฐาน e)
- `np.exp()` - ฟังก์ชันเอกซ์โพเนนเชียล (e ยกกำลัง x)
- `np.sqrt()` - รากที่สอง

ฟังก์ชันเหล่านี้คืนค่าเป็นอาร์เรย์ใหม่ที่มีขนาดเท่าอาร์เรย์ต้นฉบับ โดยแต่ละค่าถูกแปลงตามฟังก์ชันนั้น ๆ

In [10]:
### Mathematical functions ###
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Example 1: np.log 
print("np.log:", np.log(arr))                       # Natural logarithm (base e)

# Example 2: np.exp 
print("np.exp:", np.exp(arr))                       # Exponential function (e^x)

# Example 3: np.sqrt 
print("np.sqrt:", np.sqrt(arr))                     # Square root


Array: [1 2 3 4 5]
np.log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
np.exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]


**คำอธิบาย:** จุดเด่นสำคัญของ NumPy คือการคำนวณทางคณิตศาสตร์แบบ **element-wise** (คำนวณทีละคู่ตำแหน่งพร้อมกันทั้งอาร์เรย์) โดยไม่ต้องเขียนลูปเอง มี 3 กรณีหลักที่ควรเข้าใจ:
1. **อาร์เรย์กับสเกลาร์** (ตัวเลขเดี่ยว) - ตัวเลขนั้นจะถูกนำไปคำนวณกับทุกสมาชิกในอาร์เรย์ เช่น `arr + 10` คือบวก 10 เข้ากับทุกค่า
2. **อาร์เรย์กับอาร์เรย์ที่ขนาดเท่ากัน** - คำนวณตามตำแหน่งที่ตรงกัน (`a[i]` กับ `b[i]`)
3. **อาร์เรย์ที่ขนาดต่างกัน (Broadcasting)** - NumPy จะพยายาม "ขยาย" อาร์เรย์ที่เล็กกว่าให้มีขนาดตรงกับอาร์เรย์ที่ใหญ่กว่าโดยอัตโนมัติ ตามกฎการ broadcasting เช่น เมทริกซ์ขนาด (2,3) บวกกับเวกเตอร์ขนาด (3,) จะถูกขยายเวกเตอร์ให้บวกกับทุกแถว (row-wise) หรือถ้าเป็นเวกเตอร์แนวตั้งขนาด (2,1) จะถูกขยายให้บวกกับทุกคอลัมน์แทน (column-wise) - เซลล์ถัดไปแสดงตัวอย่างทั้ง 3 กรณีนี้ตามลำดับ

In [11]:
### arithmetic between arrays and scalars or arrays of different shapes ###

# Operations apply element‑wise when you combine an array with a single number (scalar):
arr = np.array([1, 2, 3, 4])

print("arr + 10:", arr + 10)                        # add scalar
print("arr * 2:", arr * 2)                          # multiply scalar
print("arr ** 2:", arr ** 2)                        # power scalar

arr + 10: [11 12 13 14]
arr * 2: [2 4 6 8]
arr ** 2: [ 1  4  9 16]


In [12]:
# Operations are element‑wise when arrays have the same shape:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b:", a + b)
print("a * b:", a * b)

a + b: [11 22 33]
a * b: [10 40 90]


In [13]:
# NumPy uses broadcasting rules to align shapes:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print("A + B:\n", A + B)                            # broadcast row-wise
print("A * B:\n", A * B)                            # multiply row-wise

A + B:
 [[11 22 33]
 [14 25 36]]
A * B:
 [[ 10  40  90]
 [ 40 100 180]]


In [14]:
# NumPy uses broadcasting rules to align shapes:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10],
              [20]])

print("A + B:\n", A + B)                            # add column-wise
print("A * B:\n", A * B)                            # multiply column-wise

A + B:
 [[11 12 13]
 [24 25 26]]
A * B:
 [[ 10  20  30]
 [ 80 100 120]]


---